project:
  type: website
  title: "Offshore Geotechnics"
  output-dir: _output
  preview:
    port: 4200
  
website:
  title: "CIEM2301: Offshore Geotechnics"
  site-url: https://triaduct.github.io/offshoregeotechnics
  announcement: 
    content: "Update 8th October: Shallow foundation example added." 
    position: below-navbar 
  comments:
    giscus: 
      repo: triaduct/offshoregeotechnics
      repo-id: "R_kgDOPlCh8A"
      category-id: "DIC_kwDOPlCh8M4CuqJo"
  sidebar:
    style: "docked"
    search: true
    reader-mode: true
    collapse-level: 1
    contents:
      - text: "🏠 Home"
        href: index.qmd
      - section: "ℹ️ Course info"
        # schedule
        # Learning objectives
        contents:
          - text: "Learning objectives"
            href: learning-objectives.qmd
          - text: "Resources"
            href: resources.qmd
          - text: "Schedule"
            href: schedule.qmd
          - text: "User guide"
            href: guide.qmd
            
      - section: "📚 Course notes"
        contents:
          - href: notes/1_intro.ipynb
          - href: notes/2_marine-geology.ipynb
          - section: "Site investigation"
            contents:
              - text: "Overview"
                href: notes/3-1_site-investigation.ipynb
              - text: "Geophysical investigation"
                href: notes/3-2_geophysical-investigation.ipynb
              - text: "Intrusive investigation"
                href: notes/3-3_geotechnical-investigation.ipynb
          - section: "Axial response of piles in sand"
            contents:
              - href: notes/4-1_piles-overview.ipynb
              - href: notes/4-2_mechanisms-sand.ipynb
              - href: notes/4-3_axial-design-sand.ipynb
          - section: "Axial response of piles in clay"
            contents:
              - href: notes/5-1_mechanisms-clay.ipynb
              - href: notes/5-2_axial-design-clay.ipynb
              - text: "Example calculation"
                href: notes/5-3_srd-clay.ipynb
          # - section: "Lateral response of piles" 
          #   contents:
          #     - text: "Basic mechanisms"
          # - section: "Cyclic and seismic loading" 
          #   contents:
          #     - text: "Basic mechanisms"
          - section: "Pile installation"
            contents:
              - text: "Overview"
                href: notes/8-1_pile-installation-overview.ipynb
              - text: "Modelling pile driving"
                href: notes/8-2_modelling-pile-driving.ipynb
          - section: "Shallow foundations"
            contents:
              - text: "Example: Thornton Bank"
                href: notes/9-1_thornton-bank-example.ipynb
              # - text: "Basic mechanisms"
              #   href: notes/shallow-foundations.ipynb

              # - text: "App: Interaction Diagram"
              #   href: playground/interaction-diagram.qmd
              # - href: playground/interaction-diagram.qmd   # The Shiny app
          # - section: "Suction-assisted installation"
          # - section: "Floating wind and anchors"
          #   contents:
          #     - text: "Basic mechanisms"

  page-footer:
    left: |
      CIEM2301: Offshore Geotechnics, Delft University of Technology
    right: |
      ![Creative Commons License](https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png) [CC BY-N-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    # left: "Copyright 2025, MY INSTITUTION"

biliography: bibliography.bib

format:
  html:
    author: "[Kevin Duffy](https://www.tudelft.nl/en/staff/k.duffy/)"
    author-meta: "Kevin Duffy"
    
    date: today
    date-modified: last-modified
    date-format: "DD MMMM YYYY"
    page-metadata:
      - modified

    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)  

    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show the code"
    warning: false  
    lightbox: true
    reader-mode: true
    
execute:
  freeze: auto   # Ensures Python scripts are only executed locally and not by github pages
  warning: false   # Don't show any code warnings